name: CI/CD Hello-App

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/hello-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup SSH for manifests repo
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone manifests repo
      run: git clone git@github.com:Guilherme-Silveira-Vaz/manifests-ci-cd.git

    - name: Increment image version
      run: |
        cd manifests-ci-cd
        LAST=$(cat VERSION)
        NEW=$((LAST + 1))
        echo "TAG=v$NEW" >> $GITHUB_ENV
        echo "$NEW" > VERSION

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:$TAG .
        docker push $IMAGE_NAME:$TAG

    - name: Update deployment image
      run: |
        cd manifests-ci-cd
        sed -i "s|image: .*|image: $IMAGE_NAME:$TAG|" deployment.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add deployment.yaml VERSION
        git commit -m "Update image to $TAG"
        git push origin main
